[package]
name = "ticket-2408"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
grillon = "0.6.0"
restest = "0.1.0"
http = "0.2"
tokio = { version = "1", features = ["full"] }
